name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, macos-latest, ubuntu-18.04]
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            shell: cmd
            mkdirs: mkdir
            rmdir: rmdir /s /q
            osDest: win
            osSpec: win32-msvc
          - os: macos-latest
            shell: sh
            mkdirs: mkdir -p
            rmdir: rm -rf
            osDest: macos
            osSpec: macx-clang
          - os: ubuntu-18.04
            shell: sh
            mkdirs: mkdir -p
            rmdir: rm -rf
            osDest: linux
            osSpec: linux-g++
           
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1  # not v2!
      with:
        path: ${{github.workspace}}/../Qt
        key: ${{ runner.os }}-QtCache
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: '6.2.2'
        host: 'windows'
        target: 'desktop'
        setup-python: 'false'
        
    - name: make destination folder
      run: |
        ${{matrix.rmdir}} ./build
        ${{matrix.mkdirs}} ./build/${{matrix.osDest}}
    - name: qMake
      working-directory: ./build/${{matrix.osDest}} 
      run: ${{env.Qt6_Dir}}/bin/qmake6 -o Makefile ../../atalierou/Atalierou.pro -spec ${{matrix.osSpec}} CONFIG+=qtquickcompiler
      
   #  - name: Configure CMake
   #    working-directory: ./atalierou 
   #    env:
   #      CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
   #    run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      working-directory: ./build/${{matrix.osDest}} 
      run: make -f Makefile qmake_all
    #   run: make --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      
