name: Build Atalierou

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
  IS_SNAPSHOT: ${{ !startsWith(github.ref, 'refs/tags/v') }}
  
jobs:
  version:
    name: "Determine version"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      release: ${{ steps.get-version.outputs.release }}

    steps:
    - name: "Get version"
      id: get-version
      run: |
        if [[ "$IS_RELEASE" == 'true' ]]; then echo "::set-output name=version::${GITHUB_REF:11}" ; fi
        if [[ "$IS_RELEASE" != 'true' ]]; then echo "::set-output name=version::$(date "+%Y.%m.%d")" ; fi
        echo "::set-output name=release::${IS_RELEASE}"
        
        
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    needs: version

    env:
      CURRENT_VERSION: ${{ needs.version.outputs.version }}
      
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # ARCH: [x86_64, i386]
        ARCH: [x86_64]
        include:
           - os: ubuntu-latest
             build_script: ./make_linux.sh
             qtInstallHost: 'linux'
             artifact_ext: AppImage 
             qtModules: 'all'
           - os: macos-latest
             build_script: ./make_macos.sh
             qtInstallHost: 'mac'
             artifact_ext: dmg 
             qtModules: 'all'
           - os: windows-latest
             build_script: .\make_windows.ps1
             qtInstallHost: 'windows'
             artifact_ext: zip 
             qtModules: 'qtshadertools qtmultimedia qtimageformats'
    runs-on: ${{ matrix.os }}       
    steps:
    - uses: actions/checkout@v2
    
 #   - name: "Cache Qt"
 #     id: cache-qt
 #     uses: actions/cache@v1  # not v2!
 #     with:
 #       path: ../Qt
 #       key: ${{ runner.os }}-$${{secrets.USE_NEW_CACHE}}-QtCache
        
    - name: "Install Qt"
      uses: jurplel/install-qt-action@v3
      with:
 #       cached: ${{ steps.cache-qt.outputs.cache-hit }}
        host: ${{matrix.qtInstallHost}} 
        target: 'desktop'
        version: '6.2.4'
        arch: 'win64_mingw'
        setup-python: 'false'
        aqtversion: '==2.1.*'
        modules: ${{matrix.qtModules}} 
        
    - name: "check mingw tools"
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        python3 -m aqt list-qt linux desktop --arch 6.2.4
        
    - name: "Install mingw tools if Windows"
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        python3 -m aqt install-tool windows desktop tools_mingw90 -O ${{env.Qt6_DIR}}
        
    - name: "launch make script"
      working-directory: .
      env:
        QT_DIR: ${{env.Qt6_DIR}}
        ARCH_NAME: ${{matrix.ARCH}}
      run: ${{matrix.build_script}}
    
    - name: "Archive artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: Atalierou_${{env.CURRENT_VERSION}}_${{matrix.ARCH}}.${{matrix.artifact_ext}} 
        path: Atalierou_${{env.CURRENT_VERSION}}_${{matrix.ARCH}}.${{matrix.artifact_ext}} 
        
    - name: "Release"
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Atalierou_${{env.CURRENT_VERSION}}_${{matrix.ARCH}}.${{matrix.artifact_ext}} 
